# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sprint3?useSSL=false&serverTimezone=UTC
    username: root
    password: Qwerty123

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
