# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    url: jdbc//proxysql.master.meliseginf.com:6612/gmuriasdb?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: none